variable "tags" {}
variable "env" {}
variable "rds_type" {}
variable "subnet_ids" {}
variable "vpc_id" {}
variable "db_sg_ingress_cidr" {}
variable "skip_final_snapshot" {}
variable "parameter_group_family" {}
variable "port" {}
variable "engine" {}
variable "engine_version" {}
variable "backup_retention_period" {}
variable "preferred_backup_window" {}
variable "instance_class" {}
variable "instance_count" {}